name: 'Settings Tray'
type: module
description: 'Provides a sidebar to configure blocks on the page.'
package: Core
# version: VERSION
# core: 8.x
dependencies:
  - drupal:block
  - drupal:toolbar
  - drupal:contextual

# Information added by Drupal.org packaging script on 2018-12-20
version: '8.x-1.4'
core: '8.x'
project: 'droopler'
datestamp: 1545295418
